team-final/albaform

- src/styles/color.scss
- src/styles/examples.scss
- src/styles/font.scss
> [feat/#10] ✨ 색상, 폰트 변수 생성

- src/styles/color.scss
- src/styles/examples.scss
resolved: #25
피그마에 잘못기입된 색상 값 수정
> [Fix/#25] 색상 변수 수정

- src/components/GNB/GNB.module.scss
- src/components/GNB/GNB.tsx
- src/components/RootHeader/RootHeader.tsx
> [feat/#7] GNB 컴포넌트 개발

- .svgrrc.js
- next.config.mjs
- src/app/applications/page.tsx
- src/app/form/[formId]/application/[applicationId]/page.tsx
- src/app/form/[formId]/apply/page.tsx
- src/app/form/[formId]/edit/page.tsx
- src/app/form/[formId]/page.tsx
- src/app/form/create/page.tsx
- src/app/forms/created/page.tsx
- src/app/forms/page.tsx
- src/app/user/me/page.tsx
- src/app/user/sign-in/page.tsx
- src/app/user/sign-up/complete/page.tsx
- src/app/user/sign-up/page.tsx
- src/lib/mock/data.ts
resolved: #38
파일 구조만 봐주시면 됩니다.
url 경로 이름, 페이지 컴포넌트 이름 지었습니다.
> [feat/#38] 페이지 라우팅

- src/app/layout.tsx
- src/app/page.module.scss
- src/app/page.tsx
- src/components/RootHeader/RootHeader.module.scss
- src/components/RootHeader/RootHeader.tsx
- src/styles/_font.scss
- src/styles/globals.css
resolved: #5
반응형 작업을 조금 새롭게 해봤는데 콘솔에 next/image 에서 priority 와 sizes 경고가 발생하네요..
이 부분은 새로운 이슈생성하고 후순위로 해결하겠습니다
> [feat/#5] 랜딩페이지 퍼블리싱

- src/components/Form/Form.tsx
resolved: #70
사용할 때 편의를 위해 주석 추가했습니다.
> [feat/#70] Form 컴포넌트 input type 주석 추가

- src/components/KakaoMap/KaKaoMap.tsx
- src/components/KakaoMap/KakaoMap.module.scss
- tsconfig.json
resolved: #ISSUE_NUMBER
https://screeching-aster-4fb.notion.site/f476396fbd7246d09abff2b81ddd4526?pvs=4
개발 전 과정을 노션에 작성해보았습니다.
+ any타입이 필수적으로 필요합니다
+ 카카오앱키를 스크립트에 담아 브라우저에서 노출이 되는데 이를 숨기는 방법이 약간 필요할 것 같습니다
+ 디자인을 어떻게 하면 좋을지 얘기 나누고 싶습니다 !
> [feat/#80] 카카오맵 지도 개발

- src/app/layout.tsx
- src/app/user/sign-in/page.tsx
- src/components/Form/Form.module.scss
- src/components/Form/Form.tsx
- src/components/MainButton/MainButton.module.scss
- src/components/VisibilityToggleButton/VisibilityToggleButton.module.scss
- src/components/VisibilityToggleButton/VisibilityToggleButton.tsx
- src/lib/types/types.ts
- src/styles/globals.css
- src/styles/reset.css
resolved: #94
Form 컴포넌트의 구조를 수정했습니다
내용은 다음과 같습니다.
```
<Form> => form 태그로 폼을 생성합니다. formId 와 submit 함수가 필요합니다.
<Form.Title> => 해당 폼의 제목을 작성할 때 사용합니다.
<Form.Fieldset> => form 의 기본 입력 단위입니다. section 태그이며, 하나 또는 여러개의 input 이 필요합니다.
<Form.Legend> => 해당 input (들)의 이름을 작성할 때 사용합니다.
<Form.Field> => 한개의 input 담는 label 단위로 htmlFor 가 필요합니다.
<Form.Label> => p 태그 입니다. 해당 input 의 값 또는 이름을 작성하고 스타일랑이 필요합니다.
<Form.Wrap> => input 을 감싸는 div 입니다. input 을 조작하는 버튼을 위치하기 위해 존재합니다.
<Form.Input> => input 태그입니다. input 에 사용되는 property 들이 필요합니다.
<Form.Textarea> => textarea 태그입니다. textarea 에 사용되는 property 들이 필요합니다.
<Form.SubmitButton> => 해당 form 의 submit 함수를 실행하는 버튼입니다. 1개만 존재 해야합니다.
```
아래 사용 예시를 따릅니다.
```tsx
<Form formId="testForm" onSubmit={handleSubmit}>
// input 하나만 다룰 때
<Form.Fieldset> …
```
> [feat/#94] Form 컴포넌트 구조 수정

- src/components/Form/Form.tsx
resolved: #117 
모든Form에서 필요한 기능들을 추합하였습니다.
formState의 mode를 onChange로 변경하였습니다.
button에서 isValid와 isSubmitting을 사용할 수 있습니다.
Submit버튼을 기존 MainButton으로 변경하였습니다.
++) 주혁님 Textarea의 옵션에서 minLength / maxLength추가하였습니다.
> [feat/#117]  Form구조 2차 수정

- package-lock.json
- src/components/Button/MainButton/MainButton.module.scss
- src/components/Button/MainButton/MainButton.tsx
- src/lib/types/types.ts
resolved: #123
MainButton 컴포넌트에 color prop 을 추가했습니다.
buttonStyle, color, type 의 기본값을 지정해주었습니다.
https://github.com/team-final/albaform/discussions/98 에 따라 함수 형태 수정
ComponentProps 의 children 을 ChildrenProps 로 분할하여 children 만 사용할 수 있도록 했습니다.
> [feat/#123] MainButton 컴포넌트 color prop 추가

- src/components/Form/Form.tsx
resolved: #126 
kakaoSearchInput 은 별도의state로  관리하려했으나 상태관리와, 통일성을 위해서,
Form내부의 state로 관리하기 위해 결합하였습니다.
> [feat/#126] kakaoSearchInput 추가

- src/app/user/sign-up/owner/step-2/page.module.scss
- src/app/user/sign-up/owner/step-2/page.tsx
- src/components/Form/Form.module.scss
- src/components/Form/Form.tsx
resolved: #110
#127 해당 브랜치 rebase하고 작업하였습니다
src/app/user/sign-up/owner/step-2 로 폴더 팠습니다.
나중에 하기 선택시, 닉네임 중복 및 null은 피해야하기때문에 가상의 이름은 반드시 만들어야합니다. 그러나 이 닉네임 자체는 사용자도 볼 수 있기 때문에, 좀 그럴싸한게 없을까 고민하다가 한번 주석으로 넣어봤습니다.
```ts
function generateRandomName(): string {
const adjectives: string[] = [
'멋있는',
'희망찬',
'행복한',
'신나는',
'귀여운',
'보람찬',
'즐거운',
'용감한',
'어여쁜',
'씩씩한',
]
const randomNum: number = Math.floor(Math.random() * 100000)
const randomAdjective: string =
adjectives[Math.floor(Math.random() * adjectives.length)]
return `${randomAdjective.charAt(0).toUpperCase() + randomAdjective.slice(1)}사장님${randomNum}`
}
```
형용사 + 사장님 + 0~100000 
까지의 랜덤한 숫자를 결합하여 닉네임을 만들어 냅니다.
ex) 행복한사장님4256 / 귀여운사장님87546
++) Form 태그안에 requiredStar 넣었습니다. input값 필수일때 label 이나 legend 옆에 그냥 넣기 편하게용. 
pattern 정규식표현
> [feat/#110] 사장님 정보입력 페이지

- package-lock.json
- package.json
- src/app/user/sign-up/owner/step-2/page.module.scss
- src/app/user/sign-up/owner/step-2/page.tsx
- src/components/Modal/Alert/AlertModal.module.scss
- src/components/Modal/Alert/AlertModal.tsx
resolved: #131 
#110 해당 브랜치위에서 rebase후 작업
react-modal 라이브러리를 통해 구현
반응형 작업
@params AlertmodalType
done or writing 일경우
테블릿 & 데스크탑
모바일
delete일 경우
테블릿 & 데스크탑
모바일
params 작성해두었으니 마우스올려보세용
```ts
'use client'
import AlertModal from '@/components/Modal/Alert/AlertModal'
import React, { useState } from 'react'
const Page = () => {
const [isModalOpen, setIsModalOpen] = useState(false) // 필수입니다.
const openModal = () => setIsModalOpen(true) // 커스텀가능합니다.
const closeModal = () => setIsModalOpen(false) // 커스텀가능합니다.
const handleConfirm = () => {
console.log('버튼이 클릭되었습니다.')
closeModal()
}
return (
<div>
<h1>예시 페이지</h1>
<button onClick={openModal}>모달 열기</button>
<AlertModal
AlertmodalType="delete"
isOpen={isModalOpen}
onRequestClose={closeModal}
onConfirm={handleConfirm}
/>
</div>
)
}
export default Page …
```
> [feat/#131] Alert 모달 제작

- src/components/Dropdown/Dropdown.module.scss
- src/components/Dropdown/Dropdown.tsx
- src/components/GlobalNavigationBar/GlobalNavigationBar.tsx
- src/lib/types/types.ts
- src/lib/utils/useToggle.ts
resolved: #143 
드롭다운 컴포넌트를 만들었습니다.
컴파운드 패턴을 선언 식으로 만들어 보았습니다.
> [feat/#143] 드롭다운 컴포넌트 추가

- src/components/Button/SignInOutButton/SignInOutButton.tsx
- src/components/FormDetails/ImageSlider/ImageSlider.css
- src/components/GlobalNavigationBar/SideBar/SideBar.tsx
resolved: #152
@JuhyeokC 에러 수정했습니다 !
> [fix/#152] 사이드바 렌더 안 되는 에러 해결

- src/app/form/[formId]/layout.tsx
- src/app/form/[formId]/page.tsx
- src/components/FormDetails/FormDetailsClient/FormDetailsClient.tsx
- src/components/FormDetails/Location/Location.module.scss
- src/components/FormDetails/Location/Location.tsx
- src/components/KakaoMap/KaKaoMap.tsx
- src/lib/api/applicationDetails.ts
- src/lib/api/formDetails.ts
> [feat/#140] 카카오 지도 삽입

- src/app/form/[formId]/layout.tsx
- src/components/Modal/MyApplication/MyApplication.tsx
- src/lib/api/applicationDetails.ts
- src/lib/queries/applicationDetailsQuery.ts
> [feat/#158] 이력서 다운로드

- src/components/FormDetails/FormDetailsClient/FormDetailsClient.module.scss
- src/components/FormDetails/FormDetailsClient/FormDetailsClient.tsx
resolved: #162 
상세보기 페이지에서 FloatingButton 의 위치를 우측 하단으로, 공유 버튼 정렬을 가로로 수정했습니다
> [fix/#162] FloatingButton 위치 수정

- package-lock.json
- package.json
- src/app/form/create/page.tsx
- src/components/DateRangePicker/DateRangePicker.tsx
- src/components/Form/Form.module.scss
- src/components/Form/Form.tsx
- src/components/FormCreate/FormCreateAside/FormCreateAside.module.scss
- src/components/FormCreate/FormCreateAside/FormCreateAside.tsx
- src/components/FormCreate/FormRecruitmentConditions/FormRecruitmentConditions.tsx
- src/components/FormCreate/FormRecruitmentContent/FormRecruitmentContent.tsx
- src/components/FormCreate/FormWorkingConditions/FormWorkingConditions.tsx
- src/lib/api/applicationDetails.ts
- src/lib/stores/formCreateStore.ts
- src/lib/types/types.ts
resolved: #164 
알바폼 생성의 단계 별 input 값 들을 확인하고 사이드메뉴에 작성중 인디케이터를 표시합니다
useFormCreateStore 의 inProgress 로 관리합니다.
작성 취소 버튼으로 form 초기화 동작과 동기화 했습니다.
> [feat/#164] 알바폼 생성 단계별 '작성중' 표시 개발

- src/app/form/create/page.module.scss
- src/app/form/create/page.tsx
- src/components/DateRangePicker/DateRangePicker.tsx
- src/components/Form/Form.tsx
- src/components/FormCreate/FormCreateAside/FormCreateAside.module.scss
- src/components/FormCreate/FormCreateAside/FormCreateAside.tsx
- src/components/FormCreate/FormCreateAsideActions/FormCreateAsideActions.module.scss
- src/components/FormCreate/FormCreateAsideActions/FormCreateAsideActions.tsx
- src/components/FormCreate/FormCreateAsideSteps/FormCreateAsideSteps.module.scss
- src/components/FormCreate/FormCreateAsideSteps/FormCreateAsideSteps.tsx
- src/components/FormCreate/FormCreateStep/FormCreateStep.tsx
- src/components/FormCreate/FormCreateTitle/FormCreateTitle.tsx
- src/components/FormCreate/FormCreateWrapper/FormCreateWrapper.tsx
- src/components/FormCreate/FormRecruitmentConditions/FormRecruitmentConditions.tsx
- src/components/FormCreate/FormRecruitmentContent/FormRecruitmentContent.tsx
- src/components/FormCreate/FormWorkingConditions/FormWorkingConditions.module.scss
- src/components/FormCreate/FormWorkingConditions/FormWorkingConditions.tsx
- src/components/FormCreate/TemporatyFormData/TemporatyFormData.module.scss
- src/components/FormCreate/TemporatyFormData/TemporatyFormData.tsx
- src/components/FormDetails/FormDetailsClient/FormDetailsClient.tsx
- src/lib/data/constants.ts
- src/lib/stores/editingFormStore.ts
- src/lib/stores/formCreateStore.ts
- src/lib/types/formTypes.ts
- src/lib/types/types.ts
resolved: #163 
localStorage 와 zustand store 를 이용해 임시저장 기능 구현.
> [feat/#163] 알바폼 만들기 임시저장 기능 개발

- src/app/user/sign-in/page.tsx
- src/app/user/sign-up/page.tsx
- src/app/user/signInSignUp.module.scss
resolved: #187 
로그인, 회원가입 페이지 디자인 적용했습니다~
> [feat/#187] 로그인, 회원가입 페이지 디자인 적용

- src/app/form/[formId]/apply/page.module.scss
- src/app/form/[formId]/apply/page.tsx
resolved: #106
알바폼 지원하기가 가능합니다.
> [feat/#106] 알바폼 지원하기 추가

- src/app/form/[formId]/apply/page.tsx
- src/app/user/sign-in/page.tsx
- src/lib/data/constants.ts
- src/lib/utils/acountGenerator.ts
resolved: #197 
테스트용 계정을 생성하고 및 무작위로 로그인되도록 연결했습니다
로그인할 때 콘솔에 사용자 정보가 출력되니 콘솔을 꼭! 확인해보세요
> [chore/#197] 테스트용 계정 생성 및 로그인

- src/app/form/[formId]/edit/page.tsx
- src/app/form/create/page.module.scss
- src/app/user/sign-in/page.tsx
- src/components/FormCreate/FormRecruitmentConditions/FormRecruitmentConditions.tsx
- src/components/FormCreate/FormRecruitmentContent/FormRecruitmentContent.tsx
- src/components/FormCreate/FormWorkingConditions/FormWorkingConditions.tsx
resolved: #193 
알바폼 수정 페이지를 생성했습니다
기존의 알바폼 생성 컴포넌트를 사용했습니다
> [feat/#193] 알바폼 수정 페이지 생성

- src/app/user/sign-in/page.tsx
- src/lib/utils/acountGenerator.ts
resolved: #197 
random 함수 사용하는 곳에
crypto 꺼 쓰래서 썻더니 에러발생해서 되돌림
> [feat/#197] crypto 제거

- src/components/FormDetails/ActionButtons/ActionButton.module.scss
- src/components/FormDetails/ActionButtons/ActionButtons.tsx
- src/components/FormDetails/ContactInfo/ContactInfo.module.scss
- src/components/FormDetails/ContactInfo/ContactInfo.tsx
- src/components/FormDetails/FormDetailsClient/FormDetailsClient.tsx
- src/components/Modal/Alert/AlertModal.module.scss
- src/components/Modal/Alert/AlertModal.tsx
resolved: #199
ActionButtons으로 공통 버튼 컴포넌트화 시켰습니다
> [feat/#199] 컴포넌트화 작업

- src/app/form/[formId]/layout.tsx
resolved: #192
여기선 아무리 router.replace를 해도 router가 안 먹더라고요
그래서 토큰으로 해봤는데 통일성이 없다고 하면 좀 더 찾아보겠습니다
> [feat/#192] 토큰 사용 리다이렉트(알바폼 상세 페이지)

- src/app/user/me/page.tsx
- src/components/Modal/UpdateInfo/Applicant/ApplicantInfoUpdate.tsx
- src/components/Modal/UpdateInfo/AuthInfoUpdate.module.scss
- src/components/Modal/UpdateInfo/Complete/CompleteInfoUpdate.module.scss
- src/components/Modal/UpdateInfo/Complete/CompleteInfoUpdate.tsx
- src/components/Modal/UpdateInfo/Owner/OwnerInfoUpdate.tsx
- src/lib/api/patchMyInfo.ts
> [feat/#206] 내 정보 수정 모달

- src/app/user/me/page.tsx
- src/components/Form/Form.tsx
- src/components/GlobalNavigationBar/SideBar/SideBar.tsx
- src/components/Modal/UpdateInfo/AuthInfoUpdate.module.scss
- src/components/Modal/UpdateInfo/Owner/OwnerInfoUpdate.tsx
- src/components/Modal/UpdateInfo/UpdateUserPassword/UpdateUserPassword.module.scss
- src/components/Modal/UpdateInfo/UpdateUserPassword/UpdateUserPassword.tsx
- src/lib/api/authAxios.ts
- src/lib/api/updateUserPassword.ts
resolved: #207 
> 추가사항
마이페이지의 비밀번호 변경 기능을 생성했습니다.
> 수정사항 
accessToken 의 이름이 token 으로 되어있던 부분을 수정했습니다
Form 컴포넌트의 submit 버튼이 활성화 되지 않는 현장을 수정했습니다.
GNB sidebar 에서 테스트용 알바폼 생성 바로가기 페이지 버튼을 제거했습니다.
마이페이지에서 정보 수정할 때 이미지를 수정하지 않는 경우에 발생하는 오류를 수정했습니다.
> [feat/#207] 마이페이지 비밀번호 변경 기능 개발

- src/app/applications/page.tsx
- src/app/form/[formId]/application/[applicationId]/page.tsx
- src/app/form/[formId]/application/page.tsx
- src/app/form/[formId]/apply/page.tsx
- src/app/form/[formId]/edit/page.tsx
- src/app/form/create/page.tsx
- src/app/forms/created/page.tsx
- src/app/forms/page.module.scss
- src/app/forms/page.tsx
- src/app/page.module.scss
- src/app/page.tsx
- src/app/user/me/page.tsx
- src/app/user/sign-in/page.tsx
- src/app/user/sign-up/complete/page.tsx
- src/app/user/sign-up/page.tsx
- src/components/Button/SignInOutButton/SignInOutButton.tsx
- src/components/FormCreate/FormCreateAsideActions/FormCreateAsideActions.tsx
- src/components/FormCreate/TemporatyFormData/TemporatyFormData.tsx
- src/components/GlobalNavigationBar/Menu/Menu.tsx
- src/components/ListCardItem/ListCardItem.tsx
- src/hooks/auth/useCreateUser.ts
- src/hooks/auth/useRefetchUser.ts
- src/hooks/auth/useSignIn.ts
- src/hooks/auth/useSignOut.ts
- src/hooks/auth/useUpdateUser.ts
- src/lib/data/constants.ts
- src/lib/data/messages.ts
- src/lib/stores/userStore.ts
- src/lib/utils/errorHandler.ts
resolved: #194
리다이렉트 전 잠깐 화면이 보이는 하이드레이션 오류가 존재합니다
Router 컴포넌트를 다른 컴포넌트를 렌더링하는 동시에 렌더링할 수 없다고 하는데
useRouter는 컴포넌트 안에서만 쓸 수 있어서 해결 방법은 아직 모르겠습니다.
> [feat/#194] user 초기값 undefined로 수정, user.role 기준 리다이렉트 추가

- src/app/applications/layout.tsx
- src/app/applications/page.module.scss
- src/app/applications/page.tsx
- src/app/forms/page.tsx
- src/app/ownersForms/layout.tsx
- src/app/ownersForms/page.module.scss
- src/app/ownersForms/page.tsx
- src/components/GlobalNavigationBar/Menu/Menu.module.scss
- src/components/GlobalNavigationBar/Menu/Menu.tsx
- src/components/ListCardItem/ListCardItem.module.scss
- src/components/ListCardItem/ListCardItem.tsx
- src/components/PostsCard/PostsCard.module.scss
- src/components/PostsCard/PostsCard.tsx
- src/lib/api/getMyApplyForms.ts
- src/lib/api/getMyForms.ts
resolved: #190
내 알바폼 -> 사장님일떄
1.
경로 src/app/ownersForms 
헤더메뉴에서 내 알바폼 클릭했을 때 role 확인하고 페이지 이동
2. 해당 페이지 무한스크롤 및 옵션들 추가 및 퍼블리싱
2-1. 폼만들기 이동
3. ListCardITem 컴포넌트에 isPublic 조건문 수정
4. 메뉴바 active옵션
(알바토크 클릭시 alert로 준비중 출력)
5. 유저role에 대해서 리다이렉트 하려고하나, 알수없는 오류(경고창) 떠서 일단 보류
(어차피 헤더바에서 분기처리해서 페이지이동)
6. 아이템 null일떄 띄우는거 테스트하고 싶으나 로그인이 안됨 ㅠㅜ
-----
내 알바폼 경로는 수정가능합니다.
> [feat/#190] 사장님 내 알바폼

- src/app/form/[formId]/application/[applicationId]/page.tsx
- src/app/form/[formId]/application/page.tsx
- src/components/FormDetails/ActionButtons/ActionButtons.tsx
- src/components/FormDetails/ApplicationDetails/ApplicationDetails.module.scss
- src/components/FormDetails/ApplicationDetails/ApplicationDetails.tsx
- src/components/FormDetails/ApplicationStatus/ApplicationStatus.module.scss
- src/components/FormDetails/ContactInfo/ContactInfo.tsx
- src/components/FormDetails/CurrentApplicationPopup/CurrentApplicationPopup.module.scss
- src/components/FormDetails/CurrentApplicationPopup/CurrentApplicationPopup.tsx
- src/components/Modal/UpdateInfo/Applicant/ApplicantInfoUpdate.tsx
- src/components/Modal/UpdateInfo/Owner/OwnerInfoUpdate.tsx
- src/lib/utils/formatDate.ts
resolved: #216
- 가게 전화번호 형식 수정
- popup 컴포넌트 오타 수정
- 내 정보 수정 imageUrl 수정
> [feat/#216] 알바폼 상세보기 페이지 수정

- next.config.mjs
- src/app/page.tsx
resolved: #219 
배포버전 이미지 파일 엑박
> [fix/#219] next 설정 파일 수정

- src/components/FormDetails/ActionButtons/ActionButtons.tsx
- src/components/FormDetails/ContactInfo/ContactInfo.module.scss
- src/components/FormDetails/ContactInfo/ContactInfo.tsx
- src/components/FormDetails/FormDetailsClient/FormDetailsClient.tsx
resolved: #222
추가적으로 사용자가 지원자 중에 있을 경우도 나누고 싶었는데 조금 에러가 나서 주석처리하고 TODO 써두었습니다.
> [feat/#222] 사용자가 작성자일 경우, 비회원일 경우 알바폼 상세보기 버튼 노출 분기

- src/app/form/[formId]/edit/page.tsx
- src/app/form/[formId]/layout.tsx
- src/hooks/auth/useSignIn.ts
resolved: #219 
로그인 훅에 사용중이 `basicAxios` 를 `authAxios` 로 수정했습니다
> [fix/#219] 로그인훅 api 인스턴스 수정

- src/app/form/create/layout.tsx
- src/app/form/create/page.module.scss
- src/app/ownersForms/page.module.scss
- src/components/Button/MainButton/MainButton.module.scss
- src/components/FormCreate/FormCreateAside/FormCreateAside.module.scss
- src/components/FormCreate/FormCreateAsideActions/FormCreateAsideActions.module.scss
- src/components/FormCreate/FormCreateAsideSteps/FormCreateAsideSteps.module.scss
- src/components/FormCreate/FormCreateAsideSteps/FormCreateAsideSteps.tsx
- src/components/FormCreate/FormCreateStep/FormCreateStep.module.scss
- src/components/FormCreate/FormCreateTitle/FormCreateTitle.module.scss
- src/components/FormCreate/FormCreateWrapper/FormCreateWrapper.module.scss
- src/components/ListCardItem/ListCardItem.module.scss
- src/styles/_variables.scss
resolved: #165 
알바폼 만들기 페이지에 반응형 디자인을 적용했습니다.
> [feat/#165] 알바폼 만들기 페이지 반응형 디자인 적용

- config/.eslintrc.json
- package-lock.json
- src/app/addtalk/layout.tsx
- src/app/addtalk/page.module.scss
- src/app/addtalk/page.tsx
- src/components/GlobalNavigationBar/Menu/Menu.tsx
- src/lib/api/albatalk.ts
- src/lib/types/formTypes.ts
- src/lib/types/types.ts
resolved: #233 
- 알바토크 작성 페이지 개발
> [feat/#233] 알바토크 작성 페이지 개발

- src/app/albatalks/page.tsx
resolved: #232
- 알바토크 목록 초기 갯수 수정
> [feat/#232] 알바토크 목록 초기 갯수 수정

- src/app/albatalks/page.module.scss
- src/components/Albatalk/Addtalk/Addtalk.tsx
- src/components/Albatalk/AlbatalkCard/AlbatalkCard.module.scss
- src/components/Albatalk/AlbatalkCard/AlbatalkCard.tsx
- src/components/Avatar/Avatar.module.scss
resolved: #232 
- 알바토크 목록 반응형 레이아웃 수정
- 알바토크 목록 생성, 수정 시 업데이트 기능 추가
> [feat/#232] 알바토크 목록 반응형 레이아웃 수정 & 생성, 수정 시 목록 업데이트

- src/app/user/me/page.tsx
- src/components/MyAlbatalk/MyAlbatalk.tsx
- src/components/MyScrap/MyScrap.tsx
- src/lib/api/getMyList.ts
- src/lib/data/constants.ts
resolved: #239 
- 마이페이지 내가 쓴 글 메뉴 개발
> [feat/#239] 마이페이지 내가 쓴 글 메뉴 개발

- src/app/albatalk/[talkId]/page.module.scss
- src/app/albatalks/page.module.scss
- src/app/user/me/page.module.scss
- src/app/user/me/page.tsx
- src/components/Albatalk/Albatalk/Albatalk.module.scss
- src/components/Comment/Comment.tsx
- src/components/MyAlbatalk/MyAlbatalk.tsx
- src/components/MyScrap/MyScrap.tsx
resolved: #239 
- 마이페이지 내가 쓴 글 메뉴 반응형 레이아웃 수정
> [feat/#239] 마이페이지 내가 쓴 글 메뉴 반응형 레이아웃 수정

- src/app/forms/page.tsx
- src/components/ListCardItem/ListCardItem.tsx
resolved: #247
- isRecruiting 값의 관리가 필요합니다. 기존 작업자의 의도를 이해하지 못했습니다.
> [fix/#247] isRecruiting 관리

- src/app/user/sign-in/page.tsx
- src/app/user/sign-up/page.tsx
resolved: #260 
에러 발생하여 페이지에서 주석 처리
> [fix/#260] 구글 oauth 주석 처리

- src/components/FormDetails/Location/Location.tsx
- src/components/Modal/MyApplication/MyApplication.tsx
- src/components/Modal/SelectStatus/SelectStatus.tsx
resolved: #250 
- <Toastify /> 중복 출력 제거
> [feat/#250] 토스트 중복 출력 수정

- src/app/layout.tsx
- src/hooks/auth/useSignOut.ts
> [feat/#269] 카카오 로그인 로딩스피너 추가

- src/components/GlobalNavigationBar/Menu/Menu.tsx
> [fix/#273] 내 알바폼 메뉴 안 나오는 문제 수정

- src/app/user/sign-out/oauth/page.tsx
- src/hooks/auth/useOauth.ts
- src/hooks/auth/useSignOut.ts
- src/hooks/useHydration.ts
> [fix/#296] 로그아웃 중복실행, 미실행 에러 해결

- .gitignore
- next.config.mjs
- package-lock.json
- package.json
- tsconfig.json
패키지 업데이트, 삭제
lint 캐싱 (변경되지 않은 부분 또 검사 X)
commonjs에서 module로 변경
css도 stylelint 적용
> [chore] 패키지 업데이트, lint 캐싱, commonjs에서 module로 변경

- .gitignore
- .husky/pre-push
- package.json
git fetch origin
git rebase origin/dev
npm run format
npm run lint
npm run tsc
npm run build
위 명령어를 push 시에 실행하고 모두 통과하면 push를 하는 hook
이었으나 VSCode에서 실행했을 때 실행 결과 보는 곳을 못 찾아서 하나의 script로 합치기만 했습니다!
> [feat] pre-push script 추가

- README.md
- next.config.mjs
- package-lock.json
- package.json
> [fix/#309] netlify 배포 삭제

- package-lock.json
- src/components/FormDetails/FormDetailsClient/FormDetailsClient.tsx
- src/lib/scripts/KakaoScript.tsx
> [fix/317] 카카오 공유 수정
